### ISSUE TITLE
Fix homebrew formula

### ISSUE THREAD

**Issue by sanikolaev** [manticoresoftware/manticoresearch-buddy#114]
https://github.com/manticoresoftware/homebrew-manticore/blob/main/Formula/manticore-buddy.rb needs a fix since there's no `./bin/build` anymore.  
  
Once fixed, please release Buddy 0.4.2. The PR is https://github.com/manticoresoftware/homebrew-manticore/pull/88

**Comment by githubmanticore** [comment]
➤ Sergey Nikolaev commented:
 

 
Fixed
