### ISSUE TITLE
Autosharding (Buddy's part)

### ISSUE THREAD

**Issue by sanikolaev** [manticoresoftware/manticoresearch-buddy#150]
Below you can find a specification of the autosharding functionality which is to be implemented on Buddy's side (there's another part for the daemon). The tasks are:  
1. review the specification  
2. if you can think of a better behaviour/algorithms/syntax - suggest it  
3. update and approve the specification  
4. implement it  
  
-----------------  
  
So imagine user does:  
  
```  
Node 1: create cluster c;  
Node 2: join cluster c at 'ip:port';  
Node 3: join cluster c at 'ip:port';  
Node 1: create table c:t(f text) shards=3 rf=2;  
```  
  
Where `shards=3` means to create 3 shards, `rf(replication factor)=2` means each shard should be exactly on 2 nodes.  
  
### First Buddy needs to prepare a shards/nodes map  
  
```sql  
 -------------------   
| shard # | nodes # |  
|--------- ---------|  
| 1       | 1,2     |  
| 2       | 2,3     |  
| 3       | 1,3     |  
 -------------------   
```  
  
Transposed:  
```sql  
 -------------------   
| node # | shards # |  
|--------- ---------|  
| 1      | 1,3      |  
| 2      | 1,2      |  
| 3      | 2,3      |  
 -------------------   
```  
  
### Actions  
  
Now it's clear what actions we need to do on what node:  
  
Node 1:  
```sql  
mkdir data/c_1_2 # where "data" is the data_dir;  
create cluster c_1_2 'c_1_2' as path;  
mkdir data/c_1_3;  
create cluster c_1_3;  
create table t_1(f text);  
alter cluster c_1_2 add t_1;  
create table t_3(f text);  
alter cluster c_1_3 add t_3;  
```  
  
Node 2:  
```sql  
mkdir data/c_1_2;  
mkdir data/c_2_3;  
create cluster c_2_3 'c_2_3' as path;  
join cluster c_1_2 at '127.0.0.1:10201' 'c_1_2' as path;  
create table t_2(f text);  
alter cluster c_2_3 add t_2;  
```  
  
Node 3:  
```  
mkdir data/c_2_3;  
join cluster c_2_3 at '127.0.0.1:20201' 'c_2_3' as path;  
mkdir data/c_1_3;  
join cluster c_1_3 at '127.0.0.1:10201' 'c_1_3' as path;  
```  
  
Create distributed indexes:  
  
Node 1:   
```sql  
create table t type='distributed' local='t_1' local='t_3' agent='127.0.0.1:20201:t_2|127.0.0.1:30201:t_2'  
```  
  
Node 2:   
```sql  
create table t type='distributed' local='t_2' local='t_1' agent='127.0.0.1:30201:t_3|127.0.0.1:10201:t_3'  
```  
  
Node 3:   
```sql  
create table t type='distributed' local='t_3' agent='127.0.0.1:10201:t_1|127.0.0.1:20201:t_1' local='t_2'  
```  
  
## Example of what should happen when I do `insert into c:t ...`  
  
This is to be done in searchd directly to note lose the performance.  
  
Node1:   
```  
insert into c_1_2:t_1 values(1,'abc');  
insert into c_1_3:t_3 values(3,'abc');  
```  
  
Node2:  
```  
insert into c_2_3:t_2 values(2,'abc');  
```  
  
## Result  
  
Now on all 3 nodes you have:  
  
```sql  
mysql> select * from t;  
 ------ ------   
| id   | f    |  
 ------ ------   
|    2 | abc  |  
|    1 | abc  |  
|    3 | abc  |  
 ------ ------   
3 rows in set (0.06 sec)  
```  
  
# Monitoring thread  
  
Buddy should have a thread to constantly monitor each replicated table to fulfill the replication factor, e.g. node 3 disappears, then Buddy has to update its internal map (if it has some, I'm just referring to it as it's easier then to visualize):  
```sql  
 -------------------   
| shard # | nodes # |  
|--------- ---------|  
| 1       | 1,2     |  
| 2       | 2,1     |  
| 3       | 1,2     |  
 -------------------   
```  
  
and create new replication clusters or use existing ones to implement the new map.  
  
# Other commands, options and new behaviour of existing commands  
  
### set global default_cluster  
```  
set global default_cluster = 'c'  
```  
  
changes the default cluster which automatically makes every NEW table belong to it.  
  
  
### show tables  
  
```  
show tables;  
```  
  
should:  
* show what cluster a table belongs to (by e.g. prepending cluster name to a table name, e.g. `c:t`, not just `t`)  
* hide special auto-created shard tables (`t_1`, `t_2`, `t_3` above)  
* Note that after `create table c:t(f text) shards=3 rf=2` `SHOW TABLES` should show `c:t` while in fact there will be 3 other tables and 3 other clusters. All that complexity should be hidden from the user.  
  
### set global shards/rf  
```sql  
set global shards=N  
```  
changes the default shards count to create NEW tables with.  
  
```sql  
set global rf=N  
```  
changes the default replication factor (rf) to create NEW tables with.  
  
### searchd.rf|shards  
  
`searchd.rf`, `searchd.shards` - corresponding settings in config (works the same way as `pseudo_sharding` and `secondary`)  
  
### rf options  
- `rf`=2-3 - means each shard should be on 3 nodes, but 2 is also ok temporarily (TBD)  
- `rf`=0.33 - means each shard should be on 33% of nodes no matter how many nodes exist  
  
### create   alter cluster add  
  
It should be possible to first create a table and then add it to a cluster:  
```sql  
create table t(f text) shards=3 rf=2  
```  
note the name is just `t`, not `<cluster>:t`, in this case we create the table (distributed) and the shards (with suffixes `_N`) locally and generate a warning saying that the table is not replicated. The `rf` value should be saved in table settings.  
  
```  
alter cluster c add t  
```  
creates the rest and move the shards around.  
  
### SHOW CLUSTERS  
  
Shows meta-clusters (i.e. created manually, not auto-created sub-clusters), tables on them and nodes info.  
  
```  
SHOW CLUSTERS;  
  
 ------ -------- ----------------------------------------- ----------------   
| name | tables | active nodes                            | inactive nodes |  
|------ --------|----------------------------------------- ----------------   
| c    | t,t2   | 127.0.0.1, 192.168.10.10, 192.168.20.20 |                |  
 ------ -------------------------------------------------- ----------------   
```  
  
Perhaps state too. To be thought through better.  
  
### SHOW TABLE STATUS  
  
```  
SHOW TABLE <name> STATUS  
```  
  
should include shards info.  
  
### DESC t TABLE  
```  
DESC t TABLE  
```  
should detect that `t` is a sharded table and show original schema of one of the shards, not that it's a distributed index. All the complexity which comes from auto-creating sub-cluster and shards should be hidden from the user.

**Comment by donhardman** [comment]
As discussed during our call, we will persist in supporting multiple clusters, albeit with a few minor modifications. We will employ three key tables to maintain order:

1. **Queue** - This table will be leveraged to execute the `join cluster` command and other similar commands on each cluster within the distributed environment.

2. **State** - This table will house the current master state for Buddy, in addition to information about all nodes and their corresponding timestamps.

3. **Tables** - This table will retain all tables, their associations with clusters and nodes, as well as all shards for each.

All system tables will be owned by the system cluster, which we manage independently and keep concealed from the user.

**Comment by donhardman** [comment]
Following our discussion today, we've decided to adopt a strategy that will safeguard sharded tables and clusters from being altered outside of Buddy. To accomplish this, we need to incorporate the following logic in the Manticoresearch daemon:

- Add a flag to the tables' meta-information (including distributed) that designates the table as protected from external modifications (this can be verified using the User-Agent header).
- Introduce a flag to the tables' meta-information that renders them invisible to requests outside of Buddy (similar to system tables).
- Develop a flag for specified clusters that prevents them from being deleted outside of Buddy, thereby guarding against the entire cluster's destruction.
- Establish a flag for clusters that makes them invisible to requests outside of Buddy.

For the daemon component, we need to devise a method for passing this flag when creating a new cluster/table as well.

**Comment by sanikolaev** [comment]
> we've decided to adopt a strategy that will safeguard sharded tables and clusters from being altered outside of Buddy

The related issue is https://github.com/manticoresoftware/manticoresearch/issues/1423

**Comment by sanikolaev** [comment]
Things to fix after testing:
* `create table t(f text) shards=2 rf=2`
* `create table t(f text) shards='2' rf='2' doesn't fail (TBD with the team)
* `create table t shards=2 rf=2`

**Comment by donhardman** [comment]
I've successfully merged everything into the main branch. However, the sharding thread is currently in "sleep" mode, as the activation logic has not yet been incorporated.

Here are the following steps:
- Ask GPT4 for scenarios that we need to address with tests.
- Develop a logic to facilitate insertions into distributed tables, making it more straightforward for testing.
- Create CLT tests on all cases we need.
- Resolve all problems identified during testing.
- Wait until we have resolved issues on the blocking side of searchd.

**Comment by donhardman** [comment]
The initial implementation of autosharding has been successfully completed and merged into the main branch.

Next, we'll be focusing on expanding test coverage. This will be guided by the following tasks:

https://github.com/manticoresoftware/manticoresearch-buddy/issues/163
https://github.com/manticoresoftware/manticoresearch-buddy/issues/162
https://github.com/manticoresoftware/manticoresearch-buddy/issues/161
https://github.com/manticoresoftware/manticoresearch-buddy/issues/160
https://github.com/manticoresoftware/manticoresearch-buddy/issues/159
https://github.com/manticoresoftware/manticoresearch-buddy/issues/158

We're closing this task now as another one has been created to carry this project through to completion, ensuring all scenarios are thoroughly tested.
