### ISSUE TITLE
Remove the 'json/' prefix from pq endpoints

### ISSUE THREAD

**Issue by githubmanticore** [manticoresoftware/manticoresearch-buddy#153]
Now the pq-related endpoints still require the `json/' prefix. We need to remove it as obsolete so that actual endpoints would match the ones described in [our documentation](https://manual.manticoresearch.com/References#HTTP-endpoints).

**Comment by githubmanticore** [comment]
➤ Stan commented:
 

 
should be fixed at dev@49722ab2ad4607ccadcd87c0c1de8fa0b0f76c69

**Comment by githubmanticore** [comment]
➤ Sergey Nikolaev commented:
 

 
Please update the changelog.

**Comment by githubmanticore** [comment]
➤ Stan commented:
 

 
should be fixed at dev@2682f6ce711e8f5819a43dcdfe1571e13fe98062

**Comment by sanikolaev** [comment]
Fixed in https://github.com/manticoresoftware/manticoresearch/commit/49722ab
