### ISSUE TITLE
Implement plugin for distributed table insertion simulation

### ISSUE THREAD

**Issue by donhardman** [manticoresoftware/manticoresearch-buddy#163]
Due to the delayed implementation of distributed insertion in Manticore Search, it appears beneficial to develop a straightforward method. 

This can be achieved through the friendly routing of failed insertions in the distributed table and inserting them using a simple algorithm like round-robin. This can be incorporated into one of the distributed tests. 

Doing so will enable us to cover auto-sharding with tests even before its implementation in the daemon.

**Comment by sanikolaev** [comment]
Decided that it'd be enough to implement emulation of a single doc insert via SQL.

**Comment by donhardman** [comment]
Implemented and added the plugin to be active on Buddy's branch: `fix/sharding`
