### ISSUE TITLE
The syntax "create table u(id bigint) shards='4' rf='1'" does not work; 

### ISSUE THREAD

**Issue by PavelShilin89** [manticoresoftware/manticoresearch-buddy#179]
When using the syntax `mysql -h0 -P1306 -e "create table u(id bigint) shards='4' rf='1'";` the table is created, but without performing sharding. 

### MRE:
1 . Go to Branch:
```
test/sharding-syntax
```
2. Running the test:
```
/Users/pavelshilin/Desktop/WORK/clt/clt test -d -t ./test/clt-tests/sharding/syntax/queries-syntax-quotes.rec ghcr.io/manticoresoftware/manticoresearch:test-kit-7012dee
echo $?
```
### Log: 
```
––– input –––
mysql -h0 -P1306 -e "create table u(id bigint) shards='4' rf='1'"; echo $?
––– output –––
0
––– input –––
mysql -h0 -P1306 -e "SHOW TABLES\G"
––– output –––
*************************** 1. row ***************************
- Index: sharding_queue
+ Index: u
Type: rt
- *************************** 2. row ***************************
- Index: sharding_state
- Type: rt
- *************************** 3. row ***************************
- Index: sharding_table
- Type: rt
- *************************** 4. row ***************************
- Index: u
- Type: distributed
- *************************** 5. row ***************************
- Index: u_s0
- Type: rt
- *************************** 6. row ***************************
- Index: u_s1
- Type: rt
- *************************** 7. row ***************************
- Index: u_s2
- Type: rt
- *************************** 8. row ***************************
- Index: u_s3
- Type: rt
- *************************** 9. row ***************************
- Index: u_s4
- Type: rt
- *************************** 10. row ***************************
- Index: u_s5
- Type: rt
- *************************** 11. row ***************************
- Index: u_s6
- Type: rt
- *************************** 12. row ***************************
- Index: u_s7
- Type: rt
- *************************** 13. row ***************************
- Index: u_s8
- Type: rt
- *************************** 14. row ***************************
- Index: u_s9
- Type: rt
––– input –––
mysql -h0 -P1306 -e "create table v(id bigint) shards=4 rf=1"; echo $?
––– output –––
0
––– input –––
mysql -h0 -P1306 -e "SHOW TABLES\G"
––– output –––
*************************** 1. row ***************************
Index: sharding_queue
Type: rt
*************************** 2. row ***************************
Index: sharding_state
Type: rt
*************************** 3. row ***************************
Index: sharding_table
Type: rt
*************************** 4. row ***************************
Index: u
Type: rt
*************************** 5. row ***************************
Index: v
Type: distributed
*************************** 6. row ***************************
Index: v_s0
Type: rt
*************************** 7. row ***************************
Index: v_s1
Type: rt
*************************** 8. row ***************************
Index: v_s2
Type: rt
*************************** 9. row ***************************
Index: v_s3
Type: rt

1
```

**Comment by tomatolog** [comment]
here is a related issue https://github.com/manticoresoftware/manticoresearch/issues/497
seems that is not planned as that is not an easy task as there a no global function that can validate all known parameters but every part validates its own subset of options and this task need improvement or try to generalize code that works with the config and validates incoming values however the source of the config and create table seems differ alot

**Comment by sanikolaev** [comment]
> that is not an easy task as there a no global function that can validate all known parameters

In this case the possible w/a can be to switch to the `create table a=123` / `alter table a=123` syntax (w/o brackets) for numbers including `rf` and `shards` and handling all non-rf/shard `a=123` in Buddy. In this case it will also remove the confusion with e.g. `create table ... optimize_cutoff='5'` as obviously it's more confusing than `create table ... optimize_cutoff=5`. However, it will increase confusion for those who are not using Buddy for some reason, but we can neglect that.

@donhardman let's do it unless someone has an objection. The plan is:
1. create a plugin which will convert `create table ... a=123 ...` to `create table ... a='123'` for all except `rf` and `shards`.
2. update the docs accordingly

**Comment by sanikolaev** [comment]
In addition to the `create table` modification, we need to do the same for the `alter` command to be consistent, e.g. how it works now:

```
mysql> alter table t optimize_cutoff='5' rt_mem_limit='1000000'; show table t settings;
--------------
alter table t optimize_cutoff='5' rt_mem_limit='1000000'
--------------

Query OK, 0 rows affected (0.02 sec)

--------------
show table t settings
--------------

+---------------+--------------------------------------------+
| Variable_name | Value                                      |
+---------------+--------------------------------------------+
| settings      | rt_mem_limit = 1000000
optimize_cutoff = 5 |
+---------------+--------------------------------------------+
1 row in set (0.00 sec)
```

It looks like the whole list is of the options that can accept numeric values is:
- optimize_cutoff
- rt_mem_limit
- index_field_lengths
- overshort_step
- phrase_boundary_step

but as discussed, let's add a general rule like `[a-zA-Z_]+\s*=\s*\d+`.

**Comment by donhardman** [comment]
The logic has been added in this pull request: https://github.com/manticoresoftware/buddy-plugin-create-table/pull/2

We might need to think about renaming the plugin, since it now covers more than just creating tables—it also handles alterations. Perhaps "modify-table" would be a good fit?

**Comment by sanikolaev** [comment]
> Perhaps "modify-table" would be a good fit?

Sounds good to me.

**Comment by donhardman** [comment]
Merged to the main, closing
