### ISSUE TITLE
Ability to create clustered and local sharded table on the same node

### ISSUE THREAD

**Issue by donhardman** [manticoresoftware/manticoresearch-buddy#188]
Currently, our auto shading logic doesn't allow us to create both local and remote tables on the same node.

We need to tweak the logic to make this possible. It should be able to handle a clustered table as well as a locally created table at the same time.

**Comment by donhardman** [comment]
It's should be fixed in `fix/sharding` branch.

@PavelShilin89 please cover this case with tests to be sure in the future also.

Test case %1. Create cluster, join cluster (can be 2 nodes), FIRST create c:a table (in cluster), SECOND create b table (without cluster). It should work

Test case %2. Create cluster, join cluster (can be 2 nodes), FIRST create b table (without cluster), SECOND create c:a table (in cluster). It should work

**Comment by PavelShilin89** [comment]
After discussion it was decided to wait for you to do the merge, then I could. At the moment my tests are ready in https://github.com/manticoresoftware/manticoresearch/pull/1754

**Comment by PavelShilin89** [comment]
Done in https://github.com/manticoresoftware/manticoresearch/pull/1948

**Comment by donhardman** [comment]
It's been merged, so I'm closing this issue.
