### ISSUE TITLE
It is not possible to create and simultaneously process a clustered table and a locally created table. 

### ISSUE THREAD

**Issue by PavelShilin89** [manticoresoftware/manticoresearch-buddy#192]
The automatic shading logic should allow us to create local and remote tables on the same node. At the moment we have managed to identify that it is impossible to create and simultaneously process a clustered table and a locally created table in a certain scenario. 

**Test case %1.** Create cluster, join cluster (can be 2 nodes), FIRST create c:a table (in cluster), SECOND create b table (without cluster). It works as expected.

**Test Case %2.** Create a cluster, join a cluster (can be 2 nodes), FIRST create table b (without cluster), SECOND create table c:a (in cluster). Doesn't work.  

### Steps to reproduce: 
**Test case %2:**
1. Launching the Docker image of Manticore Search:
```
docker run -it -e EXTRA=1 --name manticore ghcr.io/manticoresoftware/manticoresearch:test-kit-latest bash
```
2. Creating the configuration file:
```
wget https://raw.githubusercontent.com/manticoresoftware/manticoresearch/master/test/clt-tests/sharding/base/config/searchd-with-flexible-ports.conf -O /etc/manticoresearch/manticore.conf

```
3. Set up the environment and start Manticore Search:
```
apt-get update -y > /dev/null \
&& apt-get install -y git binutils > /dev/null \
&& git clone -b fix/sharding -q https://github.com/manticoresoftware/manticoresearch-buddy.git /workdir \
&& cd /workdir \
&& COMPOSER_HOME="$HOME/.config/composer" composer install -q \
&& export INSTANCE=1 \
&& mkdir -p /var/{run,lib,log}/manticore-${INSTANCE/{a,b,c,d,e,f,g,h,i,j} \
&& searchd \
&& tail -n 100 -f /var/log/manticore-${INSTANCE}/searchd.log | grep -qm1 'started v' \
&& echo "Buddy started!" \
&& export INSTANCE=2 \
&& mkdir -p /var/{run,lib,log}/manticore-${INSTANCE}/{a,b,c,d,e,f,g,h,i,j} \
&& searchd \
&& tail -n 100 -f /var/log/manticore-${INSTANCE}/searchd.log | grep -qm1 'started v' \
&& echo "Buddy started!" 
```
4. Creating and joining the cluster:
```
mysql -h0 -P1306 -e "create cluster c" \
&& mysql -h0 -P1306 -e "show status like 'cluster_c_status'\G" \
&& mysql -h0 -P2306 -e "join cluster c at '127.0.0.1:1312'" \
&& mysql -h0 -P2306 -e "show status like 'cluster_c_status'\G" 
```
5. Creating tables:
```
mysql -h0 -P1306 -e "CREATE TABLE a (title text, content text, gid uint) shards=4 rf=1" \
&& mysql -h0 -P1306 -e "CREATE TABLE c:b (title text, content text, gid uint) shards=4 rf=1"
```

### Logs: 
```
root@c4d4c03df956:/workdir# mysql -h0 -P1306 -e "create cluster c" \
&& mysql -h0 -P1306 -e "show status like 'cluster_c_status'\G" \
&& mysql -h0 -P2306 -e "join cluster c at '127.0.0.1:1312'" \
&& mysql -h0 -P2306 -e "show status like 'cluster_c_status'\G"
*************************** 1. row ***************************
Counter: cluster_c_status
  Value: primary
*************************** 1. row ***************************
Counter: cluster_c_status
  Value: primary
root@c4d4c03df956:/workdir# mysql -h0 -P1306 -e "CREATE TABLE a (title text, content text, gid uint) shards=4 rf=1" \
&& mysql -h0 -P1306 -e "CREATE TABLE c:b (title text, content text, gid uint) shards=4 rf=1"
ERROR 1064 (42000) at line 1: Waiting timeout exceeded.
```

**Comment by donhardman** [comment]
Cloning the buddy to the /workdir won't work without a `buddy_path` specified in the config. We should use the prepared config that I originally implemented in the `tests/sharding` branch for testing. You can find it here: https://github.com/manticoresoftware/manticoresearch/blob/tests/sharding/test/clt-tests/sharding/base/config/searchd-1.conf

![Image](https://github.com/manticoresoftware/manticoresearch-buddy/assets/59067742/0ea8bbf4-3727-4c6c-b95c-7a0dbeef81c2)

**Comment by PavelShilin89** [comment]
@dmitrykuzmenkov Now the error is fixed, config corrected, everything works. Closing the issue.
