### ISSUE TITLE
Update license in Buddy and plugins

### ISSUE THREAD

**Issue by sanikolaev** [manticoresoftware/manticoresearch-buddy#193]

**Comment by donhardman** [comment]
I've updated the license across all plugins and also increased the version of Buddy. Additionally, I've updated the versions of the plugins within it to ensure a consistent license throughout. You can see these changes in this commit: https://github.com/manticoresoftware/manticoresearch-buddy/commit/5f0ccd1a4c73dfa35bb72a75f1cd44f274a8acf5
