### ISSUE TITLE
Display info about each plugin on SHOW BUDDY PLUGINS

### ISSUE THREAD

**Issue by donhardman** [manticoresoftware/manticoresearch-buddy#199]
We need to enhance the `SHOW BUDDY PLUGINS` query result by including an `Info` column that displays a brief description of each plugin. Additionally, we have to add these descriptions to every plugin, detailing what the plugin does and the features it provides. We'll also need to update the common interface to make this information optional, with the default info method returning an empty string.

**Comment by donhardman** [comment]
Once we approve the texts, I'll move them to the plugins and close the issue. The pull request can be found here: https://github.com/manticoresoftware/manticoresearch/pull/1825

**Comment by sanikolaev** [comment]
https://github.com/manticoresoftware/manticoresearch/pull/1825 is approved

**Comment by sanikolaev** [comment]
The PRs lgtm. Please also review and update https://manticoresearch.com/blog/manticoresearch-buddy-pluggable-design/ if required.
