### ISSUE TITLE
Handle @timestamp column as timestamp

### ISSUE THREAD

**Issue by Nick-S-2018** [manticoresoftware/manticoresearch-buddy#218]
Logstash sends a column named `@timestamp` to Buddy.  To keep consistency between the logic of daemon and Buddy,  we need to handle it as `timestamp` regardless of its actual content.

**Comment by Nick-S-2018** [comment]
Done in https://github.com/manticoresoftware/manticoresearch-buddy/pull/219

**Comment by sanikolaev** [comment]
Please check why Manticore Serach + the updated Buddy don't pass the logstash test - https://github.com/manticoresoftware/manticoresearch/actions/runs/7976592330

If there's another issue about it - feel free to close this one.

**Comment by Nick-S-2018** [comment]
Done in https://github.com/manticoresoftware/manticoresearch-buddy/pull/222
