### ISSUE TITLE
Kibana's 'View single document' view raises an error

### ISSUE THREAD

**Issue by Nick-S-2018** [manticoresoftware/manticoresearch-buddy#245]
Currently,  a request for a single document from Kibana produces the 'Cannot find document' error.
We need to process this error with Buddy to be able to finally return the required info.

**Comment by Nick-S-2018** [comment]
Blocked by https://github.com/manticoresoftware/manticoresearch/issues/1993

**Comment by sanikolaev** [comment]
> Blocked by https://github.com/manticoresoftware/manticoresearch/issues/1993

#1933 is fixed and closed.

**Comment by Nick-S-2018** [comment]
Blocked by https://github.com/manticoresoftware/manticoresearch/issues/832

**Comment by Nick-S-2018** [comment]
Done in https://github.com/manticoresoftware/manticoresearch-buddy/commit/e0a6f27f6a2cc16669f098237704f2ee1531fab5
