### ISSUE TITLE
ENABLE/DISABLE BUDDY PLUGIN 'name'

### ISSUE THREAD

**Issue by donhardman** [manticoresoftware/manticoresearch-buddy#250]
We should add implementation to the ENABLE/DISABLE BUDDY PLUGIN 'name' queries.

We should store the state in the local environment, meaning that when Buddy restarts, we will lose the state. However, this feature is primarily needed for debugging purposes and to temporarily disable some plugins.

We should also try to migrate Sharding to the plugin system, because Sharding is now a core component of Buddy itself.

**Comment by donhardman** [comment]
Implemented at https://github.com/manticoresoftware/manticoresearch-buddy/pull/252

Right now, there's a strange problem with tests failing when the daemon is forcefully stopped using kill -9, but the main code is complete.

**Comment by donhardman** [comment]
Closing due to implemented and merged
Pull request: https://github.com/manticoresoftware/manticoresearch-buddy/pull/252
Added doc: https://github.com/manticoresoftware/manticoresearch/pull/2028

**Comment by PavelShilin89** [comment]
While working on CLT tests for ENABLE/DISABLE BUDDY plugin I detected an unusual behavior. 
1. Works fine, gives the correct error `ERROR 1064 (42000) at line 1: Plugin 'show' is disabled` 
```
mysql -h0 -P9306 -e "DISABLE BUDDY PLUGIN manticoresoftware/buddy-plugin-show"
mysql -h0 -P9306 -e "ENABLE BUDDY PLUGIN manticoresoftware/buddy-plugin-show"
``` 
2. The incorrect command does not show an error that would be obvious. 
```
mysql -h0 -P9306 -e "DISABLE BUDDY PLUGIN manticoresoftware/buddy-plugin-show-queries"
mysql -h0 -P9306 -e "ENABLE BUDDY PLUGIN manticoresoftware/buddy-plugin-show-money"
```
3. `manticoresoftware/buddy-plugin-select` doesn't work, the query keeps giving the result. 
```
mysql -h0 -P9306 -e "DISABLE BUDDY PLUGIN manticoresoftware/buddy-plugin-select"
mysql -h0 -P9306 -e "ENABLE BUDDY PLUGIN manticoresoftware/buddy-plugin-select"
```
4. `manticoresoftware/buddy-plugin-knn` works fine, gives the correct error `ERROR 1064 (42000) at line 1: Plugin 'knn' is disabled` 
```
mysql -h0 -P9306 -e "DISABLE BUDDY PLUGIN manticoresoftware/buddy-plugin-knn"
mysql -h0 -P9306 -e "select id, knn_dist() from t where knn ( image_vector, 5, 1 );"
mysql -h0 -P9306 -e "ENABLE BUDDY PLUGIN manticoresoftware/buddy-plugin-knn"
```
Also I would like to ask for better documentation, for example here https://manual.manticoresearch.com/dev/Extensions/UDFs_and_Plugins/Plugins/Enabling_and_disabling_buddy_plugins#ENABLE-BUDDY-PLUGIN and other places that use similar ENABLE BUDDY PLUGIN manticoresoftware/buddy-plugin-show-queries, now in manticore not working command .

In this example `ENABLE BUDDY PLUGIN <username/package name on https://packagist.org/>` it would be great to specify a command to get the full buddy plugin name `SHOW BUDDY PLUGIN`

**Comment by PavelShilin89** [comment]
@donhardman We discussed on the call with Sergey that we would not consider it a problem if there was no error when an incorrect query was entered.

**Comment by donhardman** [comment]
The doc was updated in this pull: https://github.com/manticoresoftware/manticoresearch/pull/2077

if it's all fine, feel free to merge.
