### ISSUE TITLE
PHPSqlParser is not good enough and hangs

### ISSUE THREAD

**Issue by donhardman** [manticoresoftware/manticoresearch-buddy#262]
### Bug Description:

While digging into the issue of why Buddy hangs during inserts, I discovered that PhpSqlParser is incredibly slow. We should investigate this library and also REMOVE all parsing or other resource-intensive operations from Payloads (currently Knn and Replace are causing it to hang).

The Payload method `hasMatch` should be lightning-fast and take virtually no time, only validating whether we should use the plugin or not.

Additionally, we should benchmark this library more thoroughly, as it appears to be a bottleneck and may need to be replaced with a faster alternative.

Here's the script I used to test it:

```php
<?php
include('vendor/autoload.php');
use PHPSQLParser\PHPSQLParser;
$parser = new PHPSQLParser();
$query = file_get_contents('./insert.sql');
$t = microtime(true);
$parsed = $parser->parse($query);
var_dump(microtime(true) - $t);
```

And the results:
```
float(265.18512988090515)
```

The file is a 1M `INSERT INTO ... VALUES ...` with multiple values.

P.S. The file can be found on dev2: `/tmp/phpsqlparser-insert.sql`

### Manticore Search Version:

Latest dev with Buddy from main

### Operating System Version:

Ubuntu Jammy

### Have you tried the latest development version?

- [X] Yes

### Internal Checklist:

<sup>To be completed by the assignee. Check off tasks that have been completed or are not applicable.</sup>
<details>

- [ ] Task estimated
- [ ] Specification created, reviewed, and approved
- [ ] Implementation completed
- [ ] Tests developed
- [ ] Documentation updated
- [ ] Documentation proofread
- [ ] Changelog updated

</details>

**Comment by djklim87** [comment]
Review https://github.com/manticoresoftware/manticoresearch-buddy/pull/263/files

**Comment by djklim87** [comment]
Done in https://github.com/manticoresoftware/manticoresearch-buddy/commit/60403a20690bdc7999ce0b511309dbc9d3186870

**Comment by sanikolaev** [comment]
@djklim87 

Did you have a chance to figure out why this is so slow?
> And the results:
> float(265.18512988090515)

**Comment by djklim87** [comment]
I made it 20 times faster, but It's still slow now (near 2 sec)

**Comment by sanikolaev** [comment]
> I made it 20 times faster, but It's still slow now (near 2 sec)

As discussed, it's ok as long as we don't have long queries passed to the parser, but we should keep this in mind and if we have to parse long queries we'd better use smth else.

**Comment by sanikolaev** [comment]
The related issue is https://github.com/greenlion/PHP-SQL-Parser/issues/385

**Comment by djklim87** [comment]
So my idea - its physically don't allow developers call directly `$sqlQueryParser::parse()` method without calling preprocessor.

Now I exposed preprocessing to `sqlQueryParser` (PR [here](https://github.com/manticoresoftware/buddy-core/pull/43/files))

Calling from Buddy's Payload looks like 
```php
if(!static::$sqlQueryParser::checkMatchPreprocessed(
    fn($request) => (
        str_contains($request->error, "P01: syntax error, unexpected integer, expecting '(' near")
        && stripos($request->payload, 'knn') !== false
        && preg_match('/\(?\s?knn\s?\(/usi', $request->payload)), $request
    )){
            return false;
}
```

@sanikolaev @donhardman Any objections?

**Comment by donhardman** [comment]
Okay, let's refine the approach for the `checkMatchAndParse` method. The idea is to automatically parse the data and store the results in a dedicated payload class variable. This way, we eliminate the need for redundant parsing or direct calls, allowing us to make the `parse` method private.

The key point is, when we have a match (indicated by `hasMatch` returning true), we're already utilizing the plugin and can confidently parse the data at this stage.

**Comment by djklim87** [comment]
Done 60c90e774faeb9d38b23ea8ab24919aad3bdd7c3
