### ISSUE TITLE
Restore uint id generated by mysqldump

### ISSUE THREAD

**Issue by donhardman** [manticoresoftware/manticoresearch-buddy#267]
### Bug Description:

We currently support unsigned bigint IDs on the Manticoresearch side, but we handle them by emulating and saving them as signed IDs. So when we create a MySQL dump, it stores the IDs as unsigned, making it impossible to restore the data.

We should catch this error on the Buddy side and modify the data to be properly inserted into Manticoresearch.

```
snikolaev@dev2:~$ mysql -P9306 -h0 -e "drop table if exists t; create table t; insert into t values(16609783591080558060); select * from t"
+----------------------+
| id                   |
+----------------------+
| -1836960482628993556 |
+----------------------+

snikolaev@dev2:~$ mysqldump -P9306 -h0 manticore t| mysql -P9306 -h0
-- Warning: column statistics not supported by the server.
ERROR 1064 (42000) at line 36: Negative document ids are not allowed
```

### Manticore Search Version:

Latest dev version

### Operating System Version:

Any

### Have you tried the latest development version?

- [X] Yes

### Internal Checklist:

<sup>To be completed by the assignee. Check off tasks that have been completed or are not applicable.</sup>
<details>

- [ ] Task estimated
- [ ] Specification created, reviewed, and approved
- [ ] Implementation completed
- [ ] Tests developed
- [ ] Documentation updated
- [ ] Documentation proofread
- [ ] Changelog updated

</details>

**Comment by donhardman** [comment]
The implementation requires GMP support on the executor side: https://github.com/manticoresoftware/executor/issues/54

This sentence is clear and concise. It conveys the requirement for GMP support on the executor side and provides a relevant link for reference. No significant changes are necessary to improve its readability or tone.

**Comment by sanikolaev** [comment]
Let's hold on. There's a chance we can handle it [right in the daemon](https://manticoresearch.slack.com/archives/D5EFHSJG4/p1714141706329839). Alexey is to create a corresponding PR.

**Comment by sanikolaev** [comment]
Done in https://github.com/manticoresoftware/manticoresearch/pull/2102
