### ISSUE TITLE
Autodetection of data types imported from Elastic

### ISSUE THREAD

**Issue by sanikolaev** [manticoresoftware/manticoresearch-buddy#268]
### Proposal:

Continuation of https://github.com/manticoresoftware/buddy-plugin-insert/issues/6 :

---

We need to be able to detect data types in cases when data is imported to Manticore from Elastic, e.g., with Elasticdump.
Now, there are three Elastic's types that are handled incorrectly when auto schema is used for data insert:

`date` - converted to `text` instead of `timestamp`
`version` - converted to `text` instead of `string`
`boolean` - converted to `text` instead of `bool` if original values are strings `true/false`

### Checklist:

<sup>To be completed by the assignee. Check off tasks that have been completed or are not applicable.</sup>
<details>

- [x] Task estimated
- [x] Specification created, reviewed and approved
- [x] Implementation completed
- [x] Tests developed
- [x] Documentation updated
- [x] Documentation proofread
- [x] Changelog updated
- [x] OpenAPI YAML updated and issue created to rebuild clients

</details>

**Comment by sanikolaev** [comment]
Blocked by https://github.com/manticoresoftware/manticoresearch/issues/1744

**Comment by Nick-S-2018** [comment]
Implemented in in https://github.com/manticoresoftware/manticoresearch-buddy/pull/333

**Comment by sanikolaev** [comment]
Reopening since the check list is not complete.

**Comment by sanikolaev** [comment]
@Nick-S-2018 pls add to this changelog too https://docs.google.com/spreadsheets/d/1mz_3dRWKs86FjRF7EIZUziUDK_2Hvhd97G0pLpxo05s/edit?gid=1102439133#gid=1102439133

**Comment by Nick-S-2018** [comment]
Done
