### ISSUE TITLE
Incorrect /cli requests hang

### ISSUE THREAD

**Issue by Nick-S-2018** [manticoresoftware/manticoresearch-buddy#271]
### Bug Description:

An incorrect request to the `/cli` endpoint hangs for a minute before the error message is returned. Moreover, all the next requests, even the correct ones, hang too until the original incorrect request is resolved.
```bash
curl localhost:9308/cli -d 'сcreate table test(title string)'

{"error":"file_get_contents(http://127.0.0.1:9312/sql?mode=raw): Failed to open stream: HTTP request failed!"}
```

### UPDATE May 9th 2024

The above maq require a restart of the searchd prior to running the `ccreate ...` query. The root cause seems to be [this one](https://github.com/manticoresoftware/manticoresearch-buddy/issues/274#issuecomment-2100245295).

### Manticore Search Version:

Manticore 6.2.13 419ecf7aa@24042801 dev

### Operating System Version:

Ubuntu 22.04.4 LTS

### Have you tried the latest development version?

- [X] Yes

### Internal Checklist:

<sup>To be completed by the assignee. Check off tasks that have been completed or are not applicable.</sup>
<details>

- [x] Task estimated
- [x] Specification created, reviewed, and approved
- [x] Implementation completed
- [x] Tests developed
- [x] Documentation updated
- [x] Documentation proofread
- [x] Changelog updated

</details>

**Comment by sanikolaev** [comment]
May be related with https://github.com/manticoresoftware/manticoresearch/issues/2116

**Comment by sanikolaev** [comment]
FYI: can't reproduce on Mac with `Manticore 6.2.13 7f012ee4f@24041611 dev (columnar 2.2.5 b4f7386@240405) (secondary 2.2.5 b4f7386@240405) (knn 2.2.5 b4f7386@240405)`

**Comment by tomatolog** [comment]
I can reproduce this case on master daemon and master buddy
```
curl localhost:9308/cli -d "сcreate table test(title string)"
{"error":"file_get_contents(http://host.docker.internal:9312/sql?mode=raw): Failed to open stream: HTTP request failed!"}
```

however after I use damon from the [http_log](https://github.com/manticoresoftware/manticoresearch/tree/http_log) and enabled to log all incoming requests from the SphinxQL and HTTP interfaces with `searchd.query_log_commands = 1` I see that daemon sends some request into buddy and buddy fails

here is the `query.log`
```
/* Fri May 03 10:12:23.167 2024 conn 14 (127.0.0.1:53514)POST /cli  */ сcreate table test(title string);
/* Fri May 03 10:12:23.167 2024 conn 14 (127.0.0.1:53514) real 0.000 */ /* DONE */;
/* Fri May 03 10:12:23.199 2024 conn 15 (127.0.0.1:53515)POST /sql?mode=raw  */ сcreate table test(title string);
/* Fri May 03 10:12:23.199 2024 conn 15 (127.0.0.1:53515) real 0.000 */ сcreate table test(title string);
/* Fri May 03 10:12:23.199 2024 conn 15 (127.0.0.1:53515) real 0.000 */ /* DONE */;
/* Fri May 03 10:12:23.200 2024 conn 15 (127.0.0.1:53515) real 0.000 */ /* DONE */;
```

here is the `searchd.log`
```
[Fri May  3 10:12:23.167 2024] [20316] [BUDDY] request to buddy:
[Fri May  3 10:12:23.167 2024] [20316] [BUDDY] {"type":"unknown json request","error":"","version":2,"message":{"path_query":"/cli","body":"сcreate table test(title string)","http_method":"POST"}}
[Fri May  3 10:12:23.184 2024] [21584] [BUDDY] [6634b887293b64.78244684] request data: {"type":"unknown json request","error":"","version":2,"message":{"path_query":"/cli","body":"сcreate table test(title string)","http_method":"POST"}} 
[Fri May  3 10:12:23.184 2024] [21584] [BUDDY] [6634b887293b64.78244684] Plugin: CliTable 
[Fri May  3 10:12:23.185 2024] [21584] [BUDDY] [6634b887293b64.78244684] CliTable payload: {"query":"\u0441create table test(title string)","path":"sql?mode=raw"} 
[Fri May  3 10:12:23.200 2024] [21948] [BUDDY] request to buddy:
[Fri May  3 10:12:23.200 2024] [21948] [BUDDY] {"type":"unknown json request","error":"P02: syntax error, unexpected $end near '(null)'","version":2,"message":{"path_query":"/sql?mode=raw","body":"сcreate table test(title string)","http_method":"POST"}}
[Fri May  3 10:13:23.270 2024] [11472] [BUDDY] [6634b887293b64.78244684] response data: {"version":2,"type":"json response","message":{"error":"file_get_contents(http:\/\/host.docker.internal:9312\/sql?mode=raw): Failed to open stream: HTTP request failed!"},"error_code":0} 
[Fri May  3 10:13:23.271 2024] [11472] [BUDDY] [6634b8c33dce97.74001405] request data: {"type":"unknown json request","error":"P02: syntax error, unexpected $end near '(null)'","version":2,"message":{"path_query":"/sql?mode=raw","body":"сcreate table test(title string)","http_method":"POST"}} 
[Fri May  3 10:13:23.272 2024] [11472] [BUDDY] [6634b8c33dce97.74001405] response data: {"version":2,"type":"json response","message":{"error":"P02: syntax error, unexpected $end near '(null)'"},"error_code":0} 
```

After `10:12:23.200` there is no request into daemon and after the last `request to buddy` at `10:12:23.200` buddy writes error `Failed to open stream: HTTP request failed!` and does nothing

**Comment by sanikolaev** [comment]
@Nick-S-2018 

In @tomatolog 's case there was:

> {"error":"file_get_contents(http:\/\/host.docker.internal:9312\/sql?mode=raw): Failed to open stream: HTTP request failed!"},"error_code":0} 

but in your case there should be another error. Can you provide it?

**Comment by sanikolaev** [comment]
> Can you provide it?

Nvmd, I see it in the initial comment:

> {"error":"file_get_contents(http://127.0.0.1:9312/sql?mode=raw): Failed to open stream: HTTP request failed!"}

**Comment by sanikolaev** [comment]
Blocked by https://github.com/manticoresoftware/manticoresearch-buddy/issues/274

**Comment by sanikolaev** [comment]
Seems to be the same issue as described here https://github.com/manticoresoftware/manticoresearch-buddy/issues/274#issuecomment-2100245295

**Comment by Nick-S-2018** [comment]
Fixed in https://github.com/manticoresoftware/manticoresearch/commit/bb40ff7a14531d30e29875c482b12990d22a3187

**Comment by sanikolaev** [comment]
> Tests developed

Tests will be implemented within https://github.com/manticoresoftware/manticoresearch-buddy/issues/274

**Comment by sanikolaev** [comment]
@Nick-S-2018 pls update the changelog https://docs.google.com/spreadsheets/d/1mz_3dRWKs86FjRF7EIZUziUDK_2Hvhd97G0pLpxo05s/edit?pli=1

**Comment by Nick-S-2018** [comment]
Done in https://github.com/manticoresoftware/manticoresearch/commit/ccfc1a0f6e6dd695d7bfd1d8b363bc0f5645dae5

**Comment by Nick-S-2018** [comment]
Ok, I've updated it.
