### ISSUE TITLE
Change the way we get telemetry for data dir size

### ISSUE THREAD

**Issue by donhardman** [manticoresoftware/manticoresearch-buddy#301]
### Proposal:

To calculate the data directory size for telemetry purposes, we currently check the path of the data directory and total up the size in bytes. However, when we encounter a directory that we don't have permission to access, the process fails with an exception. This approach isn't effective. 

Additionally, there might be extra directories that shouldn't be included in the data directory size calculation. 

To improve this, we should first read `manticore.json` and then calculate the size based on the specified files to accurately determine the total database size for telemetry.

### Checklist:

<sup>To be completed by the assignee. Check off tasks that have been completed or are not applicable.</sup>
<details>

- [x] Implementation completed
- [x] Changelog updated
- [x] OpenAPI YAML updated and issue created to rebuild clients

</details>

**Comment by donhardman** [comment]
Closing due it was merged in this commit: https://github.com/manticoresoftware/manticoresearch-buddy/commit/f944ba8c78af20aaeb1d43ea0166edc1ce25bcca

**Comment by sanikolaev** [comment]
@donhardman pls update the changelog https://docs.google.com/spreadsheets/d/1mz_3dRWKs86FjRF7EIZUziUDK_2Hvhd97G0pLpxo05s/edit?pli=1#gid=1102439133

**Comment by donhardman** [comment]
Added a new row about the change
