### ISSUE TITLE
create table if not exists ... with data failed on table exists

### ISSUE THREAD

**Issue by donhardman** [manticoresoftware/manticoresearch-buddy#325]
### Bug Description:

Here's an improved version of your text:

When we try to copy a table using `CREATE TABLE ... LIKE ... [WITH DATA]`, we can't use the `IF NOT EXISTS` option.

Expected behavior: nothing happens (no error)

```mysql
mysql> CREATE TABLE comment;
mysql> CREATE TABLE comment_1;
mysql> SHOW TABLES;
+------------------+------+
| Index            | Type |
+------------------+------+
| comment          | rt   |
| comment_1        | rt   |
+------------------+------+
mysql> CREATE TABLE comment_1 LIKE `comment` WITH DATA;
ERROR 1064 (42000): Destination table comment_1 already exists
mysql> CREATE TABLE IF NOT EXISTS comment_1 LIKE `comment` WITH DATA;
ERROR 1064 (42000): Destination table comment_1 already exists
```

### Manticore Search Version:

Latest dev version

### Operating System Version:

Ubuntu Jammy

### Have you tried the latest development version?

Yes

### Internal Checklist:

<sup>To be completed by the assignee. Check off tasks that have been completed or are not applicable.</sup>
<details>

- [x] Implementation completed
- [x] Tests developed
- [x] Documentation updated
- [x] Documentation reviewed
- [x] Changelog updated

</details>

**Comment by djklim87** [comment]
We don't support `IF NOT EXISTS` syntax for `create with data` syntax. @sanikolaev should we?

**Comment by sanikolaev** [comment]
Yes. `IF NOT EXISTS` and `WITH DATA` make sense together.

**Comment by donhardman** [comment]
Approved

**Comment by djklim87** [comment]
Done in https://github.com/manticoresoftware/manticoresearch/commit/422c9785df2784344fbca85cbbbaeaf0c336d5fd

**Comment by djklim87** [comment]
Docs updated in https://github.com/manticoresoftware/manticoresearch/commit/7b5999562998edb40823e3eb77fe97341702ba66

**Comment by djklim87** [comment]
@PavelShilin89 You should update tests for `create table with data` to start checking is `if not exists` command works

**Comment by PavelShilin89** [comment]
@djklim87 test update done in PR - https://github.com/manticoresoftware/manticoresearch/pull/2759, need review and approval for the merger.
