### ISSUE TITLE
Add support for AUTOCOMPLETE on distributed tables

### ISSUE THREAD

**Issue by donhardman** [manticoresoftware/manticoresearch-buddy#328]
### Proposal:

We should move forward with implementing the logic that will allow us to perform CALL AUTOCOMPLETE on distributed tables. To accomplish this, we need to implement parallel HTTP requests using the current Client from buddy-core. We'll then gather the data and combine it into a single response.

We should also return an error if the queried table doesn't have min_infix_len set. This is because we can't generate query suggestions in that case.

### Checklist:

<sup>To be completed by the assignee. Check off tasks that have been completed or are not applicable.</sup>
<details>

- [ ] Implementation completed
- [ ] Tests developed
- [ ] Documentation updated
- [ ] Documentation reviewed
- [ ] Changelog updated
- [x] OpenAPI YAML updated and issue created to rebuild clients

</details>

**Comment by sanikolaev** [comment]
As discussed, it's better to do it right in the daemon. Pls create an issue about it.

**Comment by donhardman** [comment]
Closing the task as it has been moved to the Manticoresearch side: https://github.com/manticoresoftware/manticoresearch/issues/2468
