### ISSUE TITLE
Check min_infix_len before we do fuzzy/autocomplete logic

### ISSUE THREAD

**Issue by donhardman** [manticoresoftware/manticoresearch-buddy#330]
We should validate if the table we interact with has min_infix_len enabled. If not, we should show an error since it won't work anyway.

We should try to cache this response (successful ones only; if there's no min_infix_len, we shouldn't cache). This will help us avoid extra queries every time the next autocomplete or fuzzy logic is performed.

### Checklist:

<sup>To be completed by the assignee. Check off tasks that have been completed or are not applicable.</sup>
<details>

- [x] Task estimated
- [x] Specification created, reviewed and approved
- [x] Implementation completed
- [x] Tests developed
- [x] Documentation updated
- [x] Documentation proofread
- [x] Changelog updated
- [x] OpenAPI YAML updated and issue created to rebuild clients

</details>

**Comment by donhardman** [comment]
Implemented special caching mechanisms in these pull requests:

- [buddy-core #66](https://github.com/manticoresoftware/buddy-core/pull/66)
- [manticoresearch-buddy #332](https://github.com/manticoresoftware/manticoresearch-buddy/pull/332)

**Comment by sanikolaev** [comment]
Let's mention this in the docs - https://github.com/manticoresoftware/manticoresearch/pull/2442

**Comment by donhardman** [comment]
The docs have been updated and are now awaiting review.

**Comment by donhardman** [comment]
Closing as it was merged: https://github.com/manticoresoftware/manticoresearch-buddy/pull/332

**Comment by sanikolaev** [comment]
Reopening to make sure it's covered by a test.

@PavelShilin89 pls take a look.

**Comment by PavelShilin89** [comment]
Done in https://github.com/manticoresoftware/manticoresearch/pull/2550
