### ISSUE TITLE
Get rid of exceptions without debug mode

### ISSUE THREAD

**Issue by donhardman** [manticoresoftware/manticoresearch-buddy#337]
### Bug Description:

We should enhance the error handling in Buddy and use critical Exceptions (e.g., instances of Error) that display necessary information. For other cases, we should show a standard error message.

Additionally, due to the Telemetry issue, we should remove all possible exceptions with traces and instead display human-readable warnings.

### Manticore Search Version:

Latest dev version

### Operating System Version:

Ubuntu Jammy

### Have you tried the latest development version?

None

### Internal Checklist:

<sup>To be completed by the assignee. Check off tasks that have been completed or are not applicable.</sup>
<details>

- [ ] Implementation completed
- [ ] Tests developed
- [ ] Documentation updated
- [ ] Documentation reviewed
- [ ] Changelog updated

</details>

**Comment by sanikolaev** [comment]
Reassigning to @Nick-S-2018 since both PRs are waiting for his review.

**Comment by donhardman** [comment]
It was merged, closing the issue
