### ISSUE TITLE
Undefined array key "id" on count by knn with doc id

### ISSUE THREAD

**Issue by donhardman** [manticoresoftware/manticoresearch-buddy#351]
### Bug Description:

```sql
mysql> SELECT count(*) FROM image WHERE knn(embeddings, 10, 2684467402) LIMIT 128;
ERROR 1064 (42000): Undefined array key "id"
```

### Manticore Search Version:

Latest dev version

### Operating System Version:

Ubuntu Jammy

### Have you tried the latest development version?

None

### Internal Checklist:

<sup>To be completed by the assignee. Check off tasks that have been completed or are not applicable.</sup>
<details>

- [x] Implementation completed
- [x] Tests developed
- [x] Documentation updated
- [x] Documentation reviewed
- [x] Changelog updated

</details>

**Comment by djklim87** [comment]
Waiting for https://github.com/manticoresoftware/manticoresearch-buddy/pull/353

**Comment by djklim87** [comment]
done in https://github.com/manticoresoftware/manticoresearch/pull/2575

**Comment by djklim87** [comment]
@sanikolaev Should Pavel add test for this issue or should I do it myself?

**Comment by sanikolaev** [comment]
@PavelShilin89 should be able to do it

**Comment by PavelShilin89** [comment]
Done in https://github.com/manticoresoftware/manticoresearch/pull/2614

**Comment by PavelShilin89** [comment]
@djklim87 needs a review and approval to merge with the master.
