### ISSUE TITLE
The replace plugin doesn't work in the replication cluster

### ISSUE THREAD

**Issue by djklim87** [manticoresoftware/manticoresearch-buddy#359]
### Bug Description:

```bash
select * from c:t
--------------

+------+------+------+
| id   | f    | f2   |
+------+------+------+
|    1 | a    | b    |
+------+------+------+
1 row in set (0.00 sec)
--- 1 out of 1 results in 0ms ---

mysql> replace into c:t set f2='c' where id=1;
--------------
replace into c:t set f2='c' where id=1
--------------

ERROR 1064 (42000): P01: syntax error, unexpected $undefined near '`c:t` (id,f,f2) VALUES (1,'a','c')'
```
Generaly replace command in cluster works fine
```
mysql> replace into c:t values(1, 'a', 'c');
--------------
replace into c:t values(1, 'a', 'c')
--------------

Query OK, 1 row affected (0.00 sec)
```

### Manticore Search Version:

6.3.7

### Operating System Version:

docker

### Have you tried the latest development version?

Yes

### Internal Checklist:

<sup>To be completed by the assignee. Check off tasks that have been completed or are not applicable.</sup>
<details>

- [x] Implementation completed
- [x] Tests developed
- [x] Documentation updated
- [x] Documentation reviewed
- [ ] Changelog updated

</details>

**Comment by djklim87** [comment]
Waiting for review https://github.com/manticoresoftware/manticoresearch-buddy/pull/361

**Comment by djklim87** [comment]
Docs https://github.com/manticoresoftware/manticoresearch/pull/2596

**Comment by sanikolaev** [comment]
> Waiting for review https://github.com/manticoresoftware/manticoresearch-buddy/pull/361

Reviewed. Merged.

**Comment by sanikolaev** [comment]
Merged [updating deps.txt](https://github.com/manticoresoftware/manticoresearch/pull/2607) in the main repo and the [docs PR](https://github.com/manticoresoftware/manticoresearch/pull/2596)

@PavelShilin89 pls update your tests on `_update`, so they cover the `cluster:table` case.

**Comment by PavelShilin89** [comment]
Testing performed in PR - https://github.com/manticoresoftware/manticoresearch/pull/2648

**Comment by sanikolaev** [comment]
@djklim87 pls update the changelog

**Comment by djklim87** [comment]
Done
