### ISSUE TITLE
Incorrect error message for KNN query: `Undefined array key 0`

### ISSUE THREAD

**Issue by PavelShilin89** [manticoresoftware/manticoresearch-buddy#363]
When executing a KNN query with an incorrect table structure, a non-informative error `Undefined array key 0` is returned. The `vector float_vector` field should be `vector float_vector knn_type=‘hnsw’ knn_dims=‘4’ hnsw_similarity=‘l2’`.

A more precise error message or correct execution of the query is expected. Easily reproducible with MRE. 

### MRE
```
--------------
CREATE TABLE knn_test (id BIGINT, model TEXT, vector float_vector)
--------------

--------------
INSERT INTO knn_test (id, model, vector) VALUES (1, 'Model_1', '[0.9012, 0.2126, 0.2879, 0.7552]')
--------------

--------------
SELECT count(*) FROM knn_test WHERE knn(vector, 10, 1)
--------------
```

**Comment by djklim87** [comment]
Waiting for review https://github.com/manticoresoftware/manticoresearch-buddy/pull/371

**Comment by donhardman** [comment]
I have approved the pull request

**Comment by djklim87** [comment]
Fixed in https://github.com/manticoresoftware/manticoresearch/commit/8f0cc03688ea3105d241075f641a0dbac347f031

**Comment by PavelShilin89** [comment]
Testing performed in PR - https://github.com/manticoresoftware/manticoresearch/pull/2677
