### ISSUE TITLE
Incorrect KNN query execution without specifying index parameters in float_vector field

### ISSUE THREAD

**Issue by PavelShilin89** [manticoresoftware/manticoresearch-buddy#368]
**Description:**

When creating a table with a float_vector field without specifying essential index parameters like knn_type, knn_dims, and hnsw_similarity, KNN queries result in an “Undefined array key 0” error. Even though the vector data is correctly formatted, the system cannot properly execute the query without these parameters, which define the index type, vector dimensions, and distance metric.

**Expected result** 

The system should return a more informative error indicating the absence of required index parameters for KNN queries. Instead of the “Undefined array key 0” error, it should clearly state that knn_type, knn_dims, and hnsw_similarity need to be specified for KNN functionality.
```
ERROR 1064 (42000): Missing required index parameters for KNN query. Ensure 'knn_type', 'knn_dims', and 'hnsw_similarity' are defined for the 'vector' field.
```
### MRE
```
--------------
CREATE TABLE knn_test (id BIGINT, model TEXT, vector float_vector)
--------------

--------------
INSERT INTO knn_test (id, model, vector) VALUES (1, 'Model_1', (0.286569,-0.031816,0.066684,0.032926))
--------------

--------------
SELECT count(*) FROM knn_test WHERE knn(vector, 10, 1)
--------------

ERROR 1064 (42000) at line 1: Undefined array key 0
```

**Comment by djklim87** [comment]
Correct response should be 
```
ERROR 1064 (42000): table knn_test: KNN index not enabled for attribute 'vector'
```

**Comment by djklim87** [comment]
Waiting for review https://github.com/manticoresoftware/manticoresearch-buddy/pull/371

**Comment by donhardman** [comment]
Approved

**Comment by djklim87** [comment]
Blocked by https://github.com/manticoresoftware/manticoresearch-buddy/issues/372

**Comment by djklim87** [comment]
Fixed in https://github.com/manticoresoftware/manticoresearch/commit/8f0cc03688ea3105d241075f641a0dbac347f031
