### ISSUE TITLE
Fuzzy search does not work in some cases

### ISSUE THREAD

**Issue by donhardman** [manticoresoftware/manticoresearch-buddy#373]
### Bug Description:

MRE:

```bash
mysql -h0 -P9306 -e "select id from comment_28798446 WHERE match('buisness Manticore interation') option fuzzy = 1, layouts = ''"
ERROR 1064 (42000) at line 1: unknown option 'fuzzy'
```

We should investigate and fix it.

### Manticore Search Version:

Latest dev version

### Operating System Version:

Ubuntu Jammy

### Have you tried the latest development version?

None

### Internal Checklist:

<sup>To be completed by the assignee. Check off tasks that have been completed or are not applicable.</sup>
<details>

- [x] Implementation completed
- [x] Tests developed
- [x] Documentation updated
- [x] Documentation reviewed
- [x] Changelog updated

</details>

**Comment by donhardman** [comment]
As discussed, we should implement the following defaults:
- `layouts = ru,us,ua` for Autocomplete
- `layouts = ''` for Fuzzy due to performance issues

**Comment by donhardman** [comment]
Fix implemented: https://github.com/manticoresoftware/manticoresearch-buddy/pull/376

We should consider adding the following tests:
1. Fuzzy options + empty layouts did not work before, e.g.,
   ```
   SELECT id FROM comment_28798446 WHERE MATCH('business Manticore interaction') OPTION fuzzy = 1, layouts = '';
   SELECT id FROM comment_28798446 WHERE MATCH('business Manticore interaction') OPTION fuzzy = 1, layouts = '';
   ```
2. Fuzzy search with "Manticore" in MATCH.

**Comment by donhardman** [comment]
@PavelShilin89  Please, proceed with adding extra tests to cover it

**Comment by PavelShilin89** [comment]
@donhardman Testing performed in PR - https://github.com/manticoresoftware/manticoresearch/pull/2756
I ask for a test review and approval for the merger.
