### ISSUE TITLE
Kafka integration fixes

### ISSUE THREAD

**Issue by donhardman** [manticoresoftware/manticoresearch-buddy#381]
### Proposal:

We should implement the following fixes in our Kafka integration:

-    Multiple queries for starting or stopping a worker (like 2-3 starts in a row) silently do nothing. We should return an error to the user when they perform 2 or more `suspend=1` actions, for example.
-    Due to the silent handling, we have an empty `catch(Throwable)` block with no handling and not even debug logging. We should consider fixing this and at least log the error.

### Checklist:

<sup>To be completed by the assignee. Check off tasks that have been completed or are not applicable.</sup>
<details>

- [x] Implementation completed
- [x] Tests developed
- [x] Documentation updated
- [x] Documentation reviewed
- [x] Changelog updated
- [x] OpenAPI YAML updated and issue created to rebuild clients

</details>

**Comment by djklim87** [comment]
Waiting for review https://github.com/manticoresoftware/manticoresearch-buddy/pull/389

**Comment by donhardman** [comment]
Approved

**Comment by djklim87** [comment]
@Pavel-Shilin need to update Kafka's CLT tests to check that it produces errors in cases below

- [ ] In case attempting to suspend already suspend MV
- [ ] In case to resume already resumed MV

**Comment by djklim87** [comment]
Fixes already [merged](https://github.com/manticoresoftware/manticoresearch/commit/422c9785df2784344fbca85cbbbaeaf0c336d5fd) to master

**Comment by PavelShilin89** [comment]
@djklim87 test update done in PR - https://github.com/manticoresoftware/manticoresearch/pull/2761, need review and approval for the merger.

**Comment by PavelShilin89** [comment]
Merged to master
