### ISSUE TITLE
Misleading error "unknown option 'fuzzy'"

### ISSUE THREAD

**Issue by sanikolaev** [manticoresoftware/manticoresearch-buddy#395]
### Bug Description:

Here:
```
mysql> drop table if exists t; create table t(a int); select * from t option fuzzy=1;
--------------
drop table if exists t
--------------

Query OK, 0 rows affected (0.00 sec)

--------------
create table t(a int)
--------------

Query OK, 0 rows affected (0.00 sec)

--------------
select * from t option fuzzy=1
--------------

ERROR 1064 (42000): unknown option 'fuzzy'
```

the error should be different, I suggest:
```
ERROR 1064 (42000): The 'fuzzy' option requires a full-text query
```

### Manticore Search Version:

Manticore 6.3.7 c91fb60b1@24111216 dev (columnar 2.3.1 30ad2d6@24100914) (secondary 2.3.1 30ad2d6@24100914) (knn 2.3.1 30ad2d6@24100914)

### Operating System Version:

Ubuntu Jammy (dev2)

### Have you tried the latest development version?

Yes

### Internal Checklist:

<sup>To be completed by the assignee. Check off tasks that have been completed or are not applicable.</sup>
<details>

- [x] Implementation completed
- [x] Tests developed
- [x] Documentation updated
- [x] Documentation reviewed
- [x] Changelog updated

</details>

**Comment by donhardman** [comment]
Implemented: https://github.com/manticoresoftware/manticoresearch-buddy/pull/397

**Comment by donhardman** [comment]
Let's add tests that MRE is fixed in this pull: https://github.com/manticoresoftware/manticoresearch/pull/2756

**Comment by PavelShilin89** [comment]
@donhardman Testing performed in PR - https://github.com/manticoresoftware/manticoresearch/pull/2756
I ask for a test review and approval for the merger.

**Comment by donhardman** [comment]
Approved

**Comment by PavelShilin89** [comment]
@sanikolaev do you need to tick the changelog?

**Comment by sanikolaev** [comment]
Done, but no record in the changelog is required since the main functionality hasn't been released yet.
