### ISSUE TITLE
Kafka plugin activates sql parser on JSON requests

### ISSUE THREAD

**Issue by donhardman** [manticoresoftware/manticoresearch-buddy#403]
### Bug Description:

We should review and optimize the `hasMatch` method of the Kafka plugin because in some cases, even when we send JSON requests to endpoints like `/insert`, the current logic uses regular expressions to match words without considering the endpoint type.

Proposal:
1. Replace regex with `stripos()` for better performance
2. Be more specific about which SQL operations the plugin supports and check for those in queries
3. Add a validation check to ensure the request is SQL-related; return false if it's not

### Manticore Search Version:

Latest dev version

### Operating System Version:

Ubuntu Jammy

### Have you tried the latest development version?

None

### Internal Checklist:

<sup>To be completed by the assignee. Check off tasks that have been completed or are not applicable.</sup>
<details>

- [ ] Implementation completed
- [ ] Tests developed
- [ ] Documentation updated
- [ ] Documentation reviewed
- [ ] Changelog updated

</details>

**Comment by djklim87** [comment]
Wait for review https://github.com/manticoresoftware/manticoresearch-buddy/pull/410

**Comment by djklim87** [comment]
Done in https://github.com/manticoresoftware/manticoresearch/commit/74f6078871b6b0524c6f27c78f2792451f7b108a
