### ISSUE TITLE
Thrown: GenericError:48> <Logged: EventHandler:69

### ISSUE THREAD

**Issue by sanikolaev** [manticoresoftware/manticoresearch-buddy#412]
### Bug Description:

Odd exception in this case:

```
snikolaev@dev2:~$ docker pull manticoresearch/manticore:dev
snikolaev@dev2:~$ docker run -e EXTRA=1 --name manticore -p 9313:9312 --rm manticoresearch/manticore:dev
snikolaev@dev2:~$ curl -s "0:9313/sql" -d "select * from products where match('ящик') option fuzzy=1"
...
listening on all interfaces for mysql, port=9306
listening on UNIX socket /var/run/mysqld/mysqld.sock
listening on all interfaces for sphinx and http(s), port=9308
listening on 172.17.0.4:9312 for sphinx and http(s)
prereading 0 tables
preread 0 tables in 0.000 sec
accepting connections
[BUDDY] started v3.0.1 '/usr/share/manticore/modules/manticore-buddy/bin/manticore-buddy --listen=http://0.0.0.0:9308/ --bind=127.0.0.1  --threads=32' at http://127.0.0.1:37367/
[BUDDY] Loaded plugins:
[BUDDY]   core: empty-string, backup, emulate-elastic, fuzzy, create, drop, insert, alias, select, show, cli-table, plugin, test, alter-column, alter-distributed-table, alter-rename-table, modify-table, knn, replace, queue, sharding, update, autocomplete
[BUDDY]   local:
[BUDDY]   extra:
[BUDDY] [X] <Thrown: GenericError:48> <Logged: EventHandler:69> <[6756d6f2c29f41.91622825] processing error>
```

### Manticore Search Version:

Manticore 6.3.9 5357ba75b@24120609 dev (columnar 2.3.1 edadc69@24112219) (secondary 2.3.1 edadc69@24112219) (knn 2.3.1 edadc69@24112219)

### Operating System Version:

Official docker

### Have you tried the latest development version?

Yes

### Internal Checklist:

<sup>To be completed by the assignee. Check off tasks that have been completed or are not applicable.</sup>
<details>

- [ ] Implementation completed
- [ ] Tests developed
- [ ] Documentation updated
- [ ] Documentation reviewed
- [ ] Changelog updated

</details>

**Comment by donhardman** [comment]
The issue here is due to daemon losing error in `/cli` endpoints
![Image](https://github.com/user-attachments/assets/68cb059f-968c-465b-980e-1f1f27d54f67)


```
[BUDDY] [6757c779ea7932.04768279] request data: {"type":"unknown json request","error":{"message":"","body":null},
"version":3,"message":{"path_query":"/cli","body":"select * from fuzzy where match('he') options fuzzy=1","http_me
thod":"POST"}}
```

**Comment by donhardman** [comment]
As per the original request, this Exception is normal and it's logged in `debug` mode because this is how we return errors. As discussed previously, we removed all extra information when it's not in debug mode for users. The reason for the exception is a missing table, so we throw it and log it for the purpose of debugging incorrect queries.

**Comment by donhardman** [comment]
As discussed, implemented logic to log only real errors (proxied): https://github.com/manticoresoftware/manticoresearch-buddy/pull/414

**Comment by donhardman** [comment]
Closing as merged to the main
