### ISSUE TITLE
Switch to pluggable architecture

### ISSUE THREAD

**Issue by sanikolaev** [manticoresoftware/manticoresearch-buddy#93]
It would be cool and easier for contributors if Buddy adapted pluggable architecture meaning each functionality would be a separate plugin, so it becomes easy to just look at how a similar functionality is implemented when you are adding a new one.

**Comment by githubmanticore** [comment]
➤ Don Hardman commented:
 

 
The pluggable system has been finalized, the pull request is here – https://github.com/manticoresoftware/manticoresearch-buddy/pull/107 
 
It should be reviewed.

**Comment by githubmanticore** [comment]
➤ Don Hardman commented:
 

 
Everything is merged into main and separated in plugins, tests pass, and the update works fine, so I'm closing this issue as done.
